### ISSUE TITLE
wrong request url?

### ISSUE THREAD

**Issue by cybergipsy2020** [isamert/orgmdb.el#3] opened 2021-05-16 00:20 UTC
I got an error message in emacs:
`Wrong authorization used for http://www.omdbapi.com/?apikey=xxxxxxx&t=I%27m%20Thinking%20of%20Ending%20Things&y=nil&type=movie`
So I tried `http://www.omdbapi.com/?apikey=xxxxxxx&t=I%27m%20Thinking%20of%20Ending%20Things&y=nil&type=movie` in the browser and it failed to fetch, but `http://www.omdbapi.com/?t=I%27m%20Thinking%20of%20Ending%20Things&y=nil&type=movie&apikey=xxxxxxx` works for me. 
Is it possible to fix this problem?

**Comment by isamert** [comment] 2021-05-16 09:33
I'm not quite sure why is this happening, because it should not matter where the `apikey` url parameter appears. I also tried and confirmed that both ways works for me. I suspected a trailing space in `apikey` might cause this but OMDb seems to handle that. Anyway, I pushed some changes that _may_ resolve this. Please let me know if it works for you.

**Comment by isamert** [comment] 2021-05-18 18:27
I'm closing this issue hoping that issue is resolved. Feel free to re-open or create a new issue.

**Closed by isamert** 2021-05-18 18:27 UTC
